version: "3.8"

services:
  mongodb:
    image: mongo:7
    container_name: encounter-forge-mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: encounter-forge-dev
    volumes:
      - mongodb-data:/data/db
    command: mongod --logpath /dev/null

volumes:
  mongodb-data:
